### PR TITLE
Bulk tests

### PR DESCRIPTION
**Pull request by dreamofaredbird**

### CODE REVIEW

**Comment by dreamofaredbird** [comment]
Hi @caoyler this is passing when I run the branch in jenkins. Shall we merge?

**Comment by caoyler** [comment]
@dreamofaredbird The tests look good, but for the assertion let's add an additional check. Bulk post returns a 200 error even if the works don't post (such as if there's a conflict or the XML is incorrectly formed). So in addition to making sure the 200 is returned let's also check that "error" is not returned. (unless you've set up an of the files to intentionally return an error).

**Comment by dreamofaredbird** [comment]
@caoyler very good shout. I hadn't factored that in so I will rework it.

**Comment by dreamofaredbird** [comment]
@caoyler as you can see I have been doing some work here testing the tests. Pretty happy they catch what we said they should. The assertFalse for broken xml is superflous however because the . tests already catches this becasue it does not return a 201 created when you get that error. I thought I could leave it in though, what do you think?

**Comment by caoyler** [comment]
@dreamofaredbird looks good. We can leave both checks for now. My suggest was to for assert false that "error" was not returned as that would have caught both types of errors we thought about and possibly others too. But this should be fine- if there's another error the works won't post and we'll see the work is missing when we do the manual review.

**Comment by dreamofaredbird** [comment]
@caoyler great thanks! I had to be specific about the error because the word 'error' is returned even when it is successfully posted

**Pull request merged**
