### PR TITLE
Peer tests

### PR DESCRIPTION
**Pull request by caoyler**

### CODE REVIEW

**Comment by dreamofaredbird** [comment]
I wonder for these, since all the ISSN are already present in the registry when we try to create a new group id we will get an 'already exists' error and we might need to think about another way of doing this?

**Comment by dreamofaredbird** [comment]
I suppose instead of checking that they are created we should check that the 409 conflict is returned
```
<response-code>409</response-code>
    <developer-message>409 Conflict: The given group-id-record already exists.</developer-message>
    <user-message>The given group-id-record already exists.</user-message>
    <error-code>9025</error-code>
```
 if it is a valid ISSN and check if you try to create one with an invalid ISSN you get the apropriate error :

```
`<response-code>400</response-code>
    <developer-message>400 Bad Request: invalid ISSN</developer-message>
    <user-message>This does not appear to be a valid ISSN</user-message>
    <error-code>9053</error-code>`
```

**Comment by caoyler** [comment]
@dreamofaredbird Here's another go with a peer-review tests and two groups tests, a read/search with an issn group id, and CRD with a non-issn group id. Please take a look, and note that the some of the peer-review tests are going to fail until https://github.com/ORCID/ORCID-Source/pull/5476 is merged.

**Comment by dreamofaredbird** [comment]
@caoyler I have run the tests using this branch. We are getting three failures One is a 500 the other two are because of duplicate posting error. I have not got to the bottom of why yet. 

https://ci.orcid.org/job/ORCID-independent-tests-step1/172/testReport/junit/

**Comment by caoyler** [comment]
@dreamofaredbird Did you miss my comment above? The peer tests won't pass until https://github.com/ORCID/ORCID-Source/pull/5476 is merged.

**Pull request merged**
